defaults:
- learning: learning_params

xml_path: "data/crawling_robot.xml"
qnet_units: [128,256,128]

project: crawling_robot
exp_name: experimentlargeforces
resume_str: null

save_path: outputs/model.ckpt

num_episodes: 1e6

w_energy_rwd: 0.2
w_pos_rwd: 0.8
k_energy_rwd: 0.1
k_pos_rwd: 100

mode: "forward"